apiVersion: v1
kind: Pod
metadata:
  name: busybox  
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: sample-volume
      mountPath: /mydata
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
  volumes:
  - name: sample-volume
    persistentVolumeClaim:
      claimName: samplepv-hostpath
  nodeSelector:
    demoserver: "true"
    
