apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-nfs-pv1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  nfs:
    path: /srv/nfs/kubedata
    server: 192.168.0.112
